AI created.
Connecting to 152.117.180.236:12345... 
Found the server. 152.117.180.236:12345
Made request to join session 1
Response is: 2
<?xml version="1.0" encoding="UTF-8"?><Gamestate><Players activePlayer="1" cycleNumber="0" numPlayers="3" turnNumber="0"/><PlanetList><Planet color="#ffee33" idNum="1" name="X" numFleets="5" owner="1" position="35,25" radius="30"/><Planet color="#aabbcc" idNum="2" name="Y" numFleets="5" owner="1" position="300,50" radius="35"/><Planet color="#00ffaa" idNum="3" name="Z" numFleets="5" owner="2" position="50,150" radius="25"/><Planet color="#aa00ee" idNum="4" name="W" numFleets="5" owner="2" position="75,300" radius="25"/><Planet color="#55cc11" idNum="5" name="S" numFleets="5" owner="1" position="300,350" radius="30"/><Planet color="#55cc11" idNum="6" name="T" numFleets="5" owner="2" position="300,350" radius="30"/></PlanetList><ConnectionList><connection>1,2</connection><connection>1,3</connection><connection>1,4</connection><connection>1,5</connection><connection>1,6</connection><connection>2,3</connection><connection>2,4</connection><connection>2,5</connection><connection>3,4</connection><connection>3,5</connection><connection>4,5</connection></ConnectionList><RegionList><Region color="#44aadd" idNum="1" name="Outer Space" owner="0" value="5"><memberList><member>1</member><member>2</member><member>3</member></memberList></Region><Region color="#44aadd" idNum="2" name="Inner Space" owner="0" value="5"><memberList><member>4</member><member>5</member><member>6</member></memberList></Region></RegionList></Gamestate>
Loading gamestate ...
Gamestate loaded.
Turn: 1 My ID: 2
It's not our turn.
Therefore I have sent a gamechange request.
Traceback (most recent call last):
  File "X:/Capstone/Repository/Capstone/Source Files/AIClient.py", line 93, in main
    ai.go()
  File "X:/Capstone/Repository/Capstone/Source Files/AIClient.py", line 71, in go
    dealWithResponse(response)
NameError: global name 'dealWithResponse' is not defined
